import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "@uploadthing/react/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./AuthProvider";
import ReactQueryProvider from "./ReactQueryProvider";
import "./globals.css";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthProvider>
            <Theme appearance="dark">
              <Container>
                <Navbar />
                <main>{children}</main>
              </Container>
            </Theme>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
